//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gender_api.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenderEnt : DbContext
    {
        public GenderEnt()
            : base("name=GenderEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<keys> keys { get; set; }
        public virtual DbSet<names> names { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
