//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gender_api.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        public int id { get; set; }
        public string key { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public System.DateTime created { get; set; }
    }
}
