//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gender_api.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.keys = new HashSet<keys>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public System.DateTime created { get; set; }
        public string company { get; set; }
    
        public virtual ICollection<keys> keys { get; set; }
    }
}
